#!/bin/bash

set -e

APP_POSTGRES_DB="${APP_POSTGRES_DB:-app}"
APP_POSTGRES_DB_USER="${APP_POSTGRES_DB_USER:-${APP_POSTGRES_DB}}"
APP_POSTGRES_DB_PASSWORD="${APP_POSTGRES_DB_PASSWORD:-${APP_POSTGRES_DB_USER}}"

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
    CREATE USER "${APP_POSTGRES_DB_USER}" PASSWORD '${APP_POSTGRES_DB_PASSWORD}';
    CREATE DATABASE "${APP_POSTGRES_DB}" OWNER "${APP_POSTGRES_DB_USER}";
EOSQL
